//Generated by CharTableConverter
//!!DO NOT EDIT
package org.freehep.graphics2d.font;

import java.util.Hashtable;

/**
 * Generated Zapfdingbats Encoding Table.
 *
 * @author org.freehep.graphics2d.font.CharTableConverter
 * @version $Id: Zapfdingbats.java,v 1.4 2009-06-22 02:18:16 hohenwarter Exp $
 */
public class Zapfdingbats extends AbstractCharTable {
	private final Hashtable<Character, String> unicodeToName = new Hashtable<>();
	private final Hashtable<String, Character> nameToUnicode = new Hashtable<>();
	private final Hashtable<String, Integer> nameToEnc = new Hashtable<>();
	private final String[] encToName = new String[256];

	public Zapfdingbats() {

		unicodeToName.put((char) 0x0020, "space");
		nameToUnicode.put("space", (char) 0x0020);
		nameToEnc.put("space", 32);
		encToName[32] = "space";

		unicodeToName.put((char) 0x2701, "a1");
		nameToUnicode.put("a1", (char) 0x2701);
		nameToEnc.put("a1", 33);
		encToName[33] = "a1";

		unicodeToName.put((char) 0x2702, "a2");
		nameToUnicode.put("a2", (char) 0x2702);
		nameToEnc.put("a2", 34);
		encToName[34] = "a2";

		unicodeToName.put((char) 0x2703, "a202");
		nameToUnicode.put("a202", (char) 0x2703);
		nameToEnc.put("a202", 35);
		encToName[35] = "a202";

		unicodeToName.put((char) 0x2704, "a3");
		nameToUnicode.put("a3", (char) 0x2704);
		nameToEnc.put("a3", 36);
		encToName[36] = "a3";

		unicodeToName.put((char) 0x260e, "a4");
		nameToUnicode.put("a4", (char) 0x260e);
		nameToEnc.put("a4", 37);
		encToName[37] = "a4";

		unicodeToName.put((char) 0x2706, "a5");
		nameToUnicode.put("a5", (char) 0x2706);
		nameToEnc.put("a5", 38);
		encToName[38] = "a5";

		unicodeToName.put((char) 0x2707, "a119");
		nameToUnicode.put("a119", (char) 0x2707);
		nameToEnc.put("a119", 39);
		encToName[39] = "a119";

		unicodeToName.put((char) 0x2708, "a118");
		nameToUnicode.put("a118", (char) 0x2708);
		nameToEnc.put("a118", 40);
		encToName[40] = "a118";

		unicodeToName.put((char) 0x2709, "a117");
		nameToUnicode.put("a117", (char) 0x2709);
		nameToEnc.put("a117", 41);
		encToName[41] = "a117";

		unicodeToName.put((char) 0x261b, "a11");
		nameToUnicode.put("a11", (char) 0x261b);
		nameToEnc.put("a11", 42);
		encToName[42] = "a11";

		unicodeToName.put((char) 0x261e, "a12");
		nameToUnicode.put("a12", (char) 0x261e);
		nameToEnc.put("a12", 43);
		encToName[43] = "a12";

		unicodeToName.put((char) 0x270c, "a13");
		nameToUnicode.put("a13", (char) 0x270c);
		nameToEnc.put("a13", 44);
		encToName[44] = "a13";

		unicodeToName.put((char) 0x270d, "a14");
		nameToUnicode.put("a14", (char) 0x270d);
		nameToEnc.put("a14", 45);
		encToName[45] = "a14";

		unicodeToName.put((char) 0x270e, "a15");
		nameToUnicode.put("a15", (char) 0x270e);
		nameToEnc.put("a15", 46);
		encToName[46] = "a15";

		unicodeToName.put((char) 0x270f, "a16");
		nameToUnicode.put("a16", (char) 0x270f);
		nameToEnc.put("a16", 47);
		encToName[47] = "a16";

		unicodeToName.put((char) 0x2710, "a105");
		nameToUnicode.put("a105", (char) 0x2710);
		nameToEnc.put("a105", 48);
		encToName[48] = "a105";

		unicodeToName.put((char) 0x2711, "a17");
		nameToUnicode.put("a17", (char) 0x2711);
		nameToEnc.put("a17", 49);
		encToName[49] = "a17";

		unicodeToName.put((char) 0x2712, "a18");
		nameToUnicode.put("a18", (char) 0x2712);
		nameToEnc.put("a18", 50);
		encToName[50] = "a18";

		unicodeToName.put((char) 0x2713, "a19");
		nameToUnicode.put("a19", (char) 0x2713);
		nameToEnc.put("a19", 51);
		encToName[51] = "a19";

		unicodeToName.put((char) 0x2714, "a20");
		nameToUnicode.put("a20", (char) 0x2714);
		nameToEnc.put("a20", 52);
		encToName[52] = "a20";

		unicodeToName.put((char) 0x2715, "a21");
		nameToUnicode.put("a21", (char) 0x2715);
		nameToEnc.put("a21", 53);
		encToName[53] = "a21";

		unicodeToName.put((char) 0x2716, "a22");
		nameToUnicode.put("a22", (char) 0x2716);
		nameToEnc.put("a22", 54);
		encToName[54] = "a22";

		unicodeToName.put((char) 0x2717, "a23");
		nameToUnicode.put("a23", (char) 0x2717);
		nameToEnc.put("a23", 55);
		encToName[55] = "a23";

		unicodeToName.put((char) 0x2718, "a24");
		nameToUnicode.put("a24", (char) 0x2718);
		nameToEnc.put("a24", 56);
		encToName[56] = "a24";

		unicodeToName.put((char) 0x2719, "a25");
		nameToUnicode.put("a25", (char) 0x2719);
		nameToEnc.put("a25", 57);
		encToName[57] = "a25";

		unicodeToName.put((char) 0x271a, "a26");
		nameToUnicode.put("a26", (char) 0x271a);
		nameToEnc.put("a26", 58);
		encToName[58] = "a26";

		unicodeToName.put((char) 0x271b, "a27");
		nameToUnicode.put("a27", (char) 0x271b);
		nameToEnc.put("a27", 59);
		encToName[59] = "a27";

		unicodeToName.put((char) 0x271c, "a28");
		nameToUnicode.put("a28", (char) 0x271c);
		nameToEnc.put("a28", 60);
		encToName[60] = "a28";

		unicodeToName.put((char) 0x271d, "a6");
		nameToUnicode.put("a6", (char) 0x271d);
		nameToEnc.put("a6", 61);
		encToName[61] = "a6";

		unicodeToName.put((char) 0x271e, "a7");
		nameToUnicode.put("a7", (char) 0x271e);
		nameToEnc.put("a7", 62);
		encToName[62] = "a7";

		unicodeToName.put((char) 0x271f, "a8");
		nameToUnicode.put("a8", (char) 0x271f);
		nameToEnc.put("a8", 63);
		encToName[63] = "a8";

		unicodeToName.put((char) 0x2720, "a9");
		nameToUnicode.put("a9", (char) 0x2720);
		nameToEnc.put("a9", 64);
		encToName[64] = "a9";

		unicodeToName.put((char) 0x2721, "a10");
		nameToUnicode.put("a10", (char) 0x2721);
		nameToEnc.put("a10", 65);
		encToName[65] = "a10";

		unicodeToName.put((char) 0x2722, "a29");
		nameToUnicode.put("a29", (char) 0x2722);
		nameToEnc.put("a29", 66);
		encToName[66] = "a29";

		unicodeToName.put((char) 0x2723, "a30");
		nameToUnicode.put("a30", (char) 0x2723);
		nameToEnc.put("a30", 67);
		encToName[67] = "a30";

		unicodeToName.put((char) 0x2724, "a31");
		nameToUnicode.put("a31", (char) 0x2724);
		nameToEnc.put("a31", 68);
		encToName[68] = "a31";

		unicodeToName.put((char) 0x2725, "a32");
		nameToUnicode.put("a32", (char) 0x2725);
		nameToEnc.put("a32", 69);
		encToName[69] = "a32";

		unicodeToName.put((char) 0x2726, "a33");
		nameToUnicode.put("a33", (char) 0x2726);
		nameToEnc.put("a33", 70);
		encToName[70] = "a33";

		unicodeToName.put((char) 0x2727, "a34");
		nameToUnicode.put("a34", (char) 0x2727);
		nameToEnc.put("a34", 71);
		encToName[71] = "a34";

		unicodeToName.put((char) 0x2605, "a35");
		nameToUnicode.put("a35", (char) 0x2605);
		nameToEnc.put("a35", 72);
		encToName[72] = "a35";

		unicodeToName.put((char) 0x2729, "a36");
		nameToUnicode.put("a36", (char) 0x2729);
		nameToEnc.put("a36", 73);
		encToName[73] = "a36";

		unicodeToName.put((char) 0x272a, "a37");
		nameToUnicode.put("a37", (char) 0x272a);
		nameToEnc.put("a37", 74);
		encToName[74] = "a37";

		unicodeToName.put((char) 0x272b, "a38");
		nameToUnicode.put("a38", (char) 0x272b);
		nameToEnc.put("a38", 75);
		encToName[75] = "a38";

		unicodeToName.put((char) 0x272c, "a39");
		nameToUnicode.put("a39", (char) 0x272c);
		nameToEnc.put("a39", 76);
		encToName[76] = "a39";

		unicodeToName.put((char) 0x272d, "a40");
		nameToUnicode.put("a40", (char) 0x272d);
		nameToEnc.put("a40", 77);
		encToName[77] = "a40";

		unicodeToName.put((char) 0x272e, "a41");
		nameToUnicode.put("a41", (char) 0x272e);
		nameToEnc.put("a41", 78);
		encToName[78] = "a41";

		unicodeToName.put((char) 0x272f, "a42");
		nameToUnicode.put("a42", (char) 0x272f);
		nameToEnc.put("a42", 79);
		encToName[79] = "a42";

		unicodeToName.put((char) 0x2730, "a43");
		nameToUnicode.put("a43", (char) 0x2730);
		nameToEnc.put("a43", 80);
		encToName[80] = "a43";

		unicodeToName.put((char) 0x2731, "a44");
		nameToUnicode.put("a44", (char) 0x2731);
		nameToEnc.put("a44", 81);
		encToName[81] = "a44";

		unicodeToName.put((char) 0x2732, "a45");
		nameToUnicode.put("a45", (char) 0x2732);
		nameToEnc.put("a45", 82);
		encToName[82] = "a45";

		unicodeToName.put((char) 0x2733, "a46");
		nameToUnicode.put("a46", (char) 0x2733);
		nameToEnc.put("a46", 83);
		encToName[83] = "a46";

		unicodeToName.put((char) 0x2734, "a47");
		nameToUnicode.put("a47", (char) 0x2734);
		nameToEnc.put("a47", 84);
		encToName[84] = "a47";

		unicodeToName.put((char) 0x2735, "a48");
		nameToUnicode.put("a48", (char) 0x2735);
		nameToEnc.put("a48", 85);
		encToName[85] = "a48";

		unicodeToName.put((char) 0x2736, "a49");
		nameToUnicode.put("a49", (char) 0x2736);
		nameToEnc.put("a49", 86);
		encToName[86] = "a49";

		unicodeToName.put((char) 0x2737, "a50");
		nameToUnicode.put("a50", (char) 0x2737);
		nameToEnc.put("a50", 87);
		encToName[87] = "a50";

		unicodeToName.put((char) 0x2738, "a51");
		nameToUnicode.put("a51", (char) 0x2738);
		nameToEnc.put("a51", 88);
		encToName[88] = "a51";

		unicodeToName.put((char) 0x2739, "a52");
		nameToUnicode.put("a52", (char) 0x2739);
		nameToEnc.put("a52", 89);
		encToName[89] = "a52";

		unicodeToName.put((char) 0x273a, "a53");
		nameToUnicode.put("a53", (char) 0x273a);
		nameToEnc.put("a53", 90);
		encToName[90] = "a53";

		unicodeToName.put((char) 0x273b, "a54");
		nameToUnicode.put("a54", (char) 0x273b);
		nameToEnc.put("a54", 91);
		encToName[91] = "a54";

		unicodeToName.put((char) 0x273c, "a55");
		nameToUnicode.put("a55", (char) 0x273c);
		nameToEnc.put("a55", 92);
		encToName[92] = "a55";

		unicodeToName.put((char) 0x273d, "a56");
		nameToUnicode.put("a56", (char) 0x273d);
		nameToEnc.put("a56", 93);
		encToName[93] = "a56";

		unicodeToName.put((char) 0x273e, "a57");
		nameToUnicode.put("a57", (char) 0x273e);
		nameToEnc.put("a57", 94);
		encToName[94] = "a57";

		unicodeToName.put((char) 0x273f, "a58");
		nameToUnicode.put("a58", (char) 0x273f);
		nameToEnc.put("a58", 95);
		encToName[95] = "a58";

		unicodeToName.put((char) 0x2740, "a59");
		nameToUnicode.put("a59", (char) 0x2740);
		nameToEnc.put("a59", 96);
		encToName[96] = "a59";

		unicodeToName.put((char) 0x2741, "a60");
		nameToUnicode.put("a60", (char) 0x2741);
		nameToEnc.put("a60", 97);
		encToName[97] = "a60";

		unicodeToName.put((char) 0x2742, "a61");
		nameToUnicode.put("a61", (char) 0x2742);
		nameToEnc.put("a61", 98);
		encToName[98] = "a61";

		unicodeToName.put((char) 0x2743, "a62");
		nameToUnicode.put("a62", (char) 0x2743);
		nameToEnc.put("a62", 99);
		encToName[99] = "a62";

		unicodeToName.put((char) 0x2744, "a63");
		nameToUnicode.put("a63", (char) 0x2744);
		nameToEnc.put("a63", 100);
		encToName[100] = "a63";

		unicodeToName.put((char) 0x2745, "a64");
		nameToUnicode.put("a64", (char) 0x2745);
		nameToEnc.put("a64", 101);
		encToName[101] = "a64";

		unicodeToName.put((char) 0x2746, "a65");
		nameToUnicode.put("a65", (char) 0x2746);
		nameToEnc.put("a65", 102);
		encToName[102] = "a65";

		unicodeToName.put((char) 0x2747, "a66");
		nameToUnicode.put("a66", (char) 0x2747);
		nameToEnc.put("a66", 103);
		encToName[103] = "a66";

		unicodeToName.put((char) 0x2748, "a67");
		nameToUnicode.put("a67", (char) 0x2748);
		nameToEnc.put("a67", 104);
		encToName[104] = "a67";

		unicodeToName.put((char) 0x2749, "a68");
		nameToUnicode.put("a68", (char) 0x2749);
		nameToEnc.put("a68", 105);
		encToName[105] = "a68";

		unicodeToName.put((char) 0x274a, "a69");
		nameToUnicode.put("a69", (char) 0x274a);
		nameToEnc.put("a69", 106);
		encToName[106] = "a69";

		unicodeToName.put((char) 0x274b, "a70");
		nameToUnicode.put("a70", (char) 0x274b);
		nameToEnc.put("a70", 107);
		encToName[107] = "a70";

		unicodeToName.put((char) 0x25cf, "a71");
		nameToUnicode.put("a71", (char) 0x25cf);
		nameToEnc.put("a71", 108);
		encToName[108] = "a71";

		unicodeToName.put((char) 0x274d, "a72");
		nameToUnicode.put("a72", (char) 0x274d);
		nameToEnc.put("a72", 109);
		encToName[109] = "a72";

		unicodeToName.put((char) 0x25a0, "a73");
		nameToUnicode.put("a73", (char) 0x25a0);
		nameToEnc.put("a73", 110);
		encToName[110] = "a73";

		unicodeToName.put((char) 0x274f, "a74");
		nameToUnicode.put("a74", (char) 0x274f);
		nameToEnc.put("a74", 111);
		encToName[111] = "a74";

		unicodeToName.put((char) 0x2750, "a203");
		nameToUnicode.put("a203", (char) 0x2750);
		nameToEnc.put("a203", 112);
		encToName[112] = "a203";

		unicodeToName.put((char) 0x2751, "a75");
		nameToUnicode.put("a75", (char) 0x2751);
		nameToEnc.put("a75", 113);
		encToName[113] = "a75";

		unicodeToName.put((char) 0x2752, "a204");
		nameToUnicode.put("a204", (char) 0x2752);
		nameToEnc.put("a204", 114);
		encToName[114] = "a204";

		unicodeToName.put((char) 0x25b2, "a76");
		nameToUnicode.put("a76", (char) 0x25b2);
		nameToEnc.put("a76", 115);
		encToName[115] = "a76";

		unicodeToName.put((char) 0x25bc, "a77");
		nameToUnicode.put("a77", (char) 0x25bc);
		nameToEnc.put("a77", 116);
		encToName[116] = "a77";

		unicodeToName.put((char) 0x25c6, "a78");
		nameToUnicode.put("a78", (char) 0x25c6);
		nameToEnc.put("a78", 117);
		encToName[117] = "a78";

		unicodeToName.put((char) 0x2756, "a79");
		nameToUnicode.put("a79", (char) 0x2756);
		nameToEnc.put("a79", 118);
		encToName[118] = "a79";

		unicodeToName.put((char) 0x25d7, "a81");
		nameToUnicode.put("a81", (char) 0x25d7);
		nameToEnc.put("a81", 119);
		encToName[119] = "a81";

		unicodeToName.put((char) 0x2758, "a82");
		nameToUnicode.put("a82", (char) 0x2758);
		nameToEnc.put("a82", 120);
		encToName[120] = "a82";

		unicodeToName.put((char) 0x2759, "a83");
		nameToUnicode.put("a83", (char) 0x2759);
		nameToEnc.put("a83", 121);
		encToName[121] = "a83";

		unicodeToName.put((char) 0x275a, "a84");
		nameToUnicode.put("a84", (char) 0x275a);
		nameToEnc.put("a84", 122);
		encToName[122] = "a84";

		unicodeToName.put((char) 0x275b, "a97");
		nameToUnicode.put("a97", (char) 0x275b);
		nameToEnc.put("a97", 123);
		encToName[123] = "a97";

		unicodeToName.put((char) 0x275c, "a98");
		nameToUnicode.put("a98", (char) 0x275c);
		nameToEnc.put("a98", 124);
		encToName[124] = "a98";

		unicodeToName.put((char) 0x275d, "a99");
		nameToUnicode.put("a99", (char) 0x275d);
		nameToEnc.put("a99", 125);
		encToName[125] = "a99";

		unicodeToName.put((char) 0x275e, "a100");
		nameToUnicode.put("a100", (char) 0x275e);
		nameToEnc.put("a100", 126);
		encToName[126] = "a100";

		unicodeToName.put((char) 0x2761, "a101");
		nameToUnicode.put("a101", (char) 0x2761);
		nameToEnc.put("a101", 161);
		encToName[161] = "a101";

		unicodeToName.put((char) 0x2762, "a102");
		nameToUnicode.put("a102", (char) 0x2762);
		nameToEnc.put("a102", 162);
		encToName[162] = "a102";

		unicodeToName.put((char) 0x2763, "a103");
		nameToUnicode.put("a103", (char) 0x2763);
		nameToEnc.put("a103", 163);
		encToName[163] = "a103";

		unicodeToName.put((char) 0x2764, "a104");
		nameToUnicode.put("a104", (char) 0x2764);
		nameToEnc.put("a104", 164);
		encToName[164] = "a104";

		unicodeToName.put((char) 0x2765, "a106");
		nameToUnicode.put("a106", (char) 0x2765);
		nameToEnc.put("a106", 165);
		encToName[165] = "a106";

		unicodeToName.put((char) 0x2766, "a107");
		nameToUnicode.put("a107", (char) 0x2766);
		nameToEnc.put("a107", 166);
		encToName[166] = "a107";

		unicodeToName.put((char) 0x2767, "a108");
		nameToUnicode.put("a108", (char) 0x2767);
		nameToEnc.put("a108", 167);
		encToName[167] = "a108";

		unicodeToName.put((char) 0x2663, "a112");
		nameToUnicode.put("a112", (char) 0x2663);
		nameToEnc.put("a112", 168);
		encToName[168] = "a112";

		unicodeToName.put((char) 0x2666, "a111");
		nameToUnicode.put("a111", (char) 0x2666);
		nameToEnc.put("a111", 169);
		encToName[169] = "a111";

		unicodeToName.put((char) 0x2665, "a110");
		nameToUnicode.put("a110", (char) 0x2665);
		nameToEnc.put("a110", 170);
		encToName[170] = "a110";

		unicodeToName.put((char) 0x2660, "a109");
		nameToUnicode.put("a109", (char) 0x2660);
		nameToEnc.put("a109", 171);
		encToName[171] = "a109";

		unicodeToName.put((char) 0x2460, "a120");
		nameToUnicode.put("a120", (char) 0x2460);
		nameToEnc.put("a120", 172);
		encToName[172] = "a120";

		unicodeToName.put((char) 0x2461, "a121");
		nameToUnicode.put("a121", (char) 0x2461);
		nameToEnc.put("a121", 173);
		encToName[173] = "a121";

		unicodeToName.put((char) 0x2462, "a122");
		nameToUnicode.put("a122", (char) 0x2462);
		nameToEnc.put("a122", 174);
		encToName[174] = "a122";

		unicodeToName.put((char) 0x2463, "a123");
		nameToUnicode.put("a123", (char) 0x2463);
		nameToEnc.put("a123", 175);
		encToName[175] = "a123";

		unicodeToName.put((char) 0x2464, "a124");
		nameToUnicode.put("a124", (char) 0x2464);
		nameToEnc.put("a124", 176);
		encToName[176] = "a124";

		unicodeToName.put((char) 0x2465, "a125");
		nameToUnicode.put("a125", (char) 0x2465);
		nameToEnc.put("a125", 177);
		encToName[177] = "a125";

		unicodeToName.put((char) 0x2466, "a126");
		nameToUnicode.put("a126", (char) 0x2466);
		nameToEnc.put("a126", 178);
		encToName[178] = "a126";

		unicodeToName.put((char) 0x2467, "a127");
		nameToUnicode.put("a127", (char) 0x2467);
		nameToEnc.put("a127", 179);
		encToName[179] = "a127";

		unicodeToName.put((char) 0x2468, "a128");
		nameToUnicode.put("a128", (char) 0x2468);
		nameToEnc.put("a128", 180);
		encToName[180] = "a128";

		unicodeToName.put((char) 0x2469, "a129");
		nameToUnicode.put("a129", (char) 0x2469);
		nameToEnc.put("a129", 181);
		encToName[181] = "a129";

		unicodeToName.put((char) 0x2776, "a130");
		nameToUnicode.put("a130", (char) 0x2776);
		nameToEnc.put("a130", 182);
		encToName[182] = "a130";

		unicodeToName.put((char) 0x2777, "a131");
		nameToUnicode.put("a131", (char) 0x2777);
		nameToEnc.put("a131", 183);
		encToName[183] = "a131";

		unicodeToName.put((char) 0x2778, "a132");
		nameToUnicode.put("a132", (char) 0x2778);
		nameToEnc.put("a132", 184);
		encToName[184] = "a132";

		unicodeToName.put((char) 0x2779, "a133");
		nameToUnicode.put("a133", (char) 0x2779);
		nameToEnc.put("a133", 185);
		encToName[185] = "a133";

		unicodeToName.put((char) 0x277a, "a134");
		nameToUnicode.put("a134", (char) 0x277a);
		nameToEnc.put("a134", 186);
		encToName[186] = "a134";

		unicodeToName.put((char) 0x277b, "a135");
		nameToUnicode.put("a135", (char) 0x277b);
		nameToEnc.put("a135", 187);
		encToName[187] = "a135";

		unicodeToName.put((char) 0x277c, "a136");
		nameToUnicode.put("a136", (char) 0x277c);
		nameToEnc.put("a136", 188);
		encToName[188] = "a136";

		unicodeToName.put((char) 0x277d, "a137");
		nameToUnicode.put("a137", (char) 0x277d);
		nameToEnc.put("a137", 189);
		encToName[189] = "a137";

		unicodeToName.put((char) 0x277e, "a138");
		nameToUnicode.put("a138", (char) 0x277e);
		nameToEnc.put("a138", 190);
		encToName[190] = "a138";

		unicodeToName.put((char) 0x277f, "a139");
		nameToUnicode.put("a139", (char) 0x277f);
		nameToEnc.put("a139", 191);
		encToName[191] = "a139";

		unicodeToName.put((char) 0x2780, "a140");
		nameToUnicode.put("a140", (char) 0x2780);
		nameToEnc.put("a140", 192);
		encToName[192] = "a140";

		unicodeToName.put((char) 0x2781, "a141");
		nameToUnicode.put("a141", (char) 0x2781);
		nameToEnc.put("a141", 193);
		encToName[193] = "a141";

		unicodeToName.put((char) 0x2782, "a142");
		nameToUnicode.put("a142", (char) 0x2782);
		nameToEnc.put("a142", 194);
		encToName[194] = "a142";

		unicodeToName.put((char) 0x2783, "a143");
		nameToUnicode.put("a143", (char) 0x2783);
		nameToEnc.put("a143", 195);
		encToName[195] = "a143";

		unicodeToName.put((char) 0x2784, "a144");
		nameToUnicode.put("a144", (char) 0x2784);
		nameToEnc.put("a144", 196);
		encToName[196] = "a144";

		unicodeToName.put((char) 0x2785, "a145");
		nameToUnicode.put("a145", (char) 0x2785);
		nameToEnc.put("a145", 197);
		encToName[197] = "a145";

		unicodeToName.put((char) 0x2786, "a146");
		nameToUnicode.put("a146", (char) 0x2786);
		nameToEnc.put("a146", 198);
		encToName[198] = "a146";

		unicodeToName.put((char) 0x2787, "a147");
		nameToUnicode.put("a147", (char) 0x2787);
		nameToEnc.put("a147", 199);
		encToName[199] = "a147";

		unicodeToName.put((char) 0x2788, "a148");
		nameToUnicode.put("a148", (char) 0x2788);
		nameToEnc.put("a148", 200);
		encToName[200] = "a148";

		unicodeToName.put((char) 0x2789, "a149");
		nameToUnicode.put("a149", (char) 0x2789);
		nameToEnc.put("a149", 201);
		encToName[201] = "a149";

		unicodeToName.put((char) 0x278a, "a150");
		nameToUnicode.put("a150", (char) 0x278a);
		nameToEnc.put("a150", 202);
		encToName[202] = "a150";

		unicodeToName.put((char) 0x278b, "a151");
		nameToUnicode.put("a151", (char) 0x278b);
		nameToEnc.put("a151", 203);
		encToName[203] = "a151";

		unicodeToName.put((char) 0x278c, "a152");
		nameToUnicode.put("a152", (char) 0x278c);
		nameToEnc.put("a152", 204);
		encToName[204] = "a152";

		unicodeToName.put((char) 0x278d, "a153");
		nameToUnicode.put("a153", (char) 0x278d);
		nameToEnc.put("a153", 205);
		encToName[205] = "a153";

		unicodeToName.put((char) 0x278e, "a154");
		nameToUnicode.put("a154", (char) 0x278e);
		nameToEnc.put("a154", 206);
		encToName[206] = "a154";

		unicodeToName.put((char) 0x278f, "a155");
		nameToUnicode.put("a155", (char) 0x278f);
		nameToEnc.put("a155", 207);
		encToName[207] = "a155";

		unicodeToName.put((char) 0x2790, "a156");
		nameToUnicode.put("a156", (char) 0x2790);
		nameToEnc.put("a156", 208);
		encToName[208] = "a156";

		unicodeToName.put((char) 0x2791, "a157");
		nameToUnicode.put("a157", (char) 0x2791);
		nameToEnc.put("a157", 209);
		encToName[209] = "a157";

		unicodeToName.put((char) 0x2792, "a158");
		nameToUnicode.put("a158", (char) 0x2792);
		nameToEnc.put("a158", 210);
		encToName[210] = "a158";

		unicodeToName.put((char) 0x2793, "a159");
		nameToUnicode.put("a159", (char) 0x2793);
		nameToEnc.put("a159", 211);
		encToName[211] = "a159";

		unicodeToName.put((char) 0x2794, "a160");
		nameToUnicode.put("a160", (char) 0x2794);
		nameToEnc.put("a160", 212);
		encToName[212] = "a160";

		unicodeToName.put((char) 0x2192, "a161");
		nameToUnicode.put("a161", (char) 0x2192);
		nameToEnc.put("a161", 213);
		encToName[213] = "a161";

		unicodeToName.put((char) 0x2194, "a163");
		nameToUnicode.put("a163", (char) 0x2194);
		nameToEnc.put("a163", 214);
		encToName[214] = "a163";

		unicodeToName.put((char) 0x2195, "a164");
		nameToUnicode.put("a164", (char) 0x2195);
		nameToEnc.put("a164", 215);
		encToName[215] = "a164";

		unicodeToName.put((char) 0x2798, "a196");
		nameToUnicode.put("a196", (char) 0x2798);
		nameToEnc.put("a196", 216);
		encToName[216] = "a196";

		unicodeToName.put((char) 0x2799, "a165");
		nameToUnicode.put("a165", (char) 0x2799);
		nameToEnc.put("a165", 217);
		encToName[217] = "a165";

		unicodeToName.put((char) 0x279a, "a192");
		nameToUnicode.put("a192", (char) 0x279a);
		nameToEnc.put("a192", 218);
		encToName[218] = "a192";

		unicodeToName.put((char) 0x279b, "a166");
		nameToUnicode.put("a166", (char) 0x279b);
		nameToEnc.put("a166", 219);
		encToName[219] = "a166";

		unicodeToName.put((char) 0x279c, "a167");
		nameToUnicode.put("a167", (char) 0x279c);
		nameToEnc.put("a167", 220);
		encToName[220] = "a167";

		unicodeToName.put((char) 0x279d, "a168");
		nameToUnicode.put("a168", (char) 0x279d);
		nameToEnc.put("a168", 221);
		encToName[221] = "a168";

		unicodeToName.put((char) 0x279e, "a169");
		nameToUnicode.put("a169", (char) 0x279e);
		nameToEnc.put("a169", 222);
		encToName[222] = "a169";

		unicodeToName.put((char) 0x279f, "a170");
		nameToUnicode.put("a170", (char) 0x279f);
		nameToEnc.put("a170", 223);
		encToName[223] = "a170";

		unicodeToName.put((char) 0x27a0, "a171");
		nameToUnicode.put("a171", (char) 0x27a0);
		nameToEnc.put("a171", 224);
		encToName[224] = "a171";

		unicodeToName.put((char) 0x27a1, "a172");
		nameToUnicode.put("a172", (char) 0x27a1);
		nameToEnc.put("a172", 225);
		encToName[225] = "a172";

		unicodeToName.put((char) 0x27a2, "a173");
		nameToUnicode.put("a173", (char) 0x27a2);
		nameToEnc.put("a173", 226);
		encToName[226] = "a173";

		unicodeToName.put((char) 0x27a3, "a162");
		nameToUnicode.put("a162", (char) 0x27a3);
		nameToEnc.put("a162", 227);
		encToName[227] = "a162";

		unicodeToName.put((char) 0x27a4, "a174");
		nameToUnicode.put("a174", (char) 0x27a4);
		nameToEnc.put("a174", 228);
		encToName[228] = "a174";

		unicodeToName.put((char) 0x27a5, "a175");
		nameToUnicode.put("a175", (char) 0x27a5);
		nameToEnc.put("a175", 229);
		encToName[229] = "a175";

		unicodeToName.put((char) 0x27a6, "a176");
		nameToUnicode.put("a176", (char) 0x27a6);
		nameToEnc.put("a176", 230);
		encToName[230] = "a176";

		unicodeToName.put((char) 0x27a7, "a177");
		nameToUnicode.put("a177", (char) 0x27a7);
		nameToEnc.put("a177", 231);
		encToName[231] = "a177";

		unicodeToName.put((char) 0x27a8, "a178");
		nameToUnicode.put("a178", (char) 0x27a8);
		nameToEnc.put("a178", 232);
		encToName[232] = "a178";

		unicodeToName.put((char) 0x27a9, "a179");
		nameToUnicode.put("a179", (char) 0x27a9);
		nameToEnc.put("a179", 233);
		encToName[233] = "a179";

		unicodeToName.put((char) 0x27aa, "a193");
		nameToUnicode.put("a193", (char) 0x27aa);
		nameToEnc.put("a193", 234);
		encToName[234] = "a193";

		unicodeToName.put((char) 0x27ab, "a180");
		nameToUnicode.put("a180", (char) 0x27ab);
		nameToEnc.put("a180", 235);
		encToName[235] = "a180";

		unicodeToName.put((char) 0x27ac, "a199");
		nameToUnicode.put("a199", (char) 0x27ac);
		nameToEnc.put("a199", 236);
		encToName[236] = "a199";

		unicodeToName.put((char) 0x27ad, "a181");
		nameToUnicode.put("a181", (char) 0x27ad);
		nameToEnc.put("a181", 237);
		encToName[237] = "a181";

		unicodeToName.put((char) 0x27ae, "a200");
		nameToUnicode.put("a200", (char) 0x27ae);
		nameToEnc.put("a200", 238);
		encToName[238] = "a200";

		unicodeToName.put((char) 0x27af, "a182");
		nameToUnicode.put("a182", (char) 0x27af);
		nameToEnc.put("a182", 239);
		encToName[239] = "a182";

		unicodeToName.put((char) 0x27b1, "a201");
		nameToUnicode.put("a201", (char) 0x27b1);
		nameToEnc.put("a201", 241);
		encToName[241] = "a201";

		unicodeToName.put((char) 0x27b2, "a183");
		nameToUnicode.put("a183", (char) 0x27b2);
		nameToEnc.put("a183", 242);
		encToName[242] = "a183";

		unicodeToName.put((char) 0x27b3, "a184");
		nameToUnicode.put("a184", (char) 0x27b3);
		nameToEnc.put("a184", 243);
		encToName[243] = "a184";

		unicodeToName.put((char) 0x27b4, "a197");
		nameToUnicode.put("a197", (char) 0x27b4);
		nameToEnc.put("a197", 244);
		encToName[244] = "a197";

		unicodeToName.put((char) 0x27b5, "a185");
		nameToUnicode.put("a185", (char) 0x27b5);
		nameToEnc.put("a185", 245);
		encToName[245] = "a185";

		unicodeToName.put((char) 0x27b6, "a194");
		nameToUnicode.put("a194", (char) 0x27b6);
		nameToEnc.put("a194", 246);
		encToName[246] = "a194";

		unicodeToName.put((char) 0x27b7, "a198");
		nameToUnicode.put("a198", (char) 0x27b7);
		nameToEnc.put("a198", 247);
		encToName[247] = "a198";

		unicodeToName.put((char) 0x27b8, "a186");
		nameToUnicode.put("a186", (char) 0x27b8);
		nameToEnc.put("a186", 248);
		encToName[248] = "a186";

		unicodeToName.put((char) 0x27b9, "a195");
		nameToUnicode.put("a195", (char) 0x27b9);
		nameToEnc.put("a195", 249);
		encToName[249] = "a195";

		unicodeToName.put((char) 0x27ba, "a187");
		nameToUnicode.put("a187", (char) 0x27ba);
		nameToEnc.put("a187", 250);
		encToName[250] = "a187";

		unicodeToName.put((char) 0x27bb, "a188");
		nameToUnicode.put("a188", (char) 0x27bb);
		nameToEnc.put("a188", 251);
		encToName[251] = "a188";

		unicodeToName.put((char) 0x27bc, "a189");
		nameToUnicode.put("a189", (char) 0x27bc);
		nameToEnc.put("a189", 252);
		encToName[252] = "a189";

		unicodeToName.put((char) 0x27bd, "a190");
		nameToUnicode.put("a190", (char) 0x27bd);
		nameToEnc.put("a190", 253);
		encToName[253] = "a190";

		unicodeToName.put((char) 0x27be, "a191");
		nameToUnicode.put("a191", (char) 0x27be);
		nameToEnc.put("a191", 254);
		encToName[254] = "a191";

	}

	@Override
	public String toName(Character c) {
		return unicodeToName.get(c);
	}

	@Override
	public String toName(int enc) {
		if (enc != 0) {
			return encToName[enc];
		}
		return null;
	}

	@Override
	public int toEncoding(String name) {
		return nameToEnc.get(name);
	}

	@Override
	public char toUnicode(String name) {
		return nameToUnicode.get(name);
	}

	@Override
	public String getName() {
		return "Zapfdingbats";
	}

	@Override
	public String getEncoding() {
		return "";
	}

}
